server:
  Port: 1508
  Addr: http://localhost:1508/

sqlserver:
  Server: ..
  Username: ..
  Password: ..
  Port: ..
  Database: ..
  MaxOpenConns: 25
  MaxIdleConns: 25
  ConnMaxLifeTime: 5

redis:
  Addr: ...
  Password: ...
  Username: ...
  DB: 0

auth:
  AccessKey: ...
  RefreshKey: ...
  AccessExp: 20
  RefreshExp: 1440
  AutoLogoffMinutes: 10
